EMBEDDING_MODEL_OPENAI = "OpenAI"
EMBEDDING_MODEL_OPENSOURCE = "OpenSource"
EMBEDDING_MODEL_OPENAI_HYBRID = "OpenAI-Hybrid"
EMBEDDING_MODEL_OPENSOURCE_HYBRID = "OpenSource-Hybrid"
EMBEDDING_MODEL_SPARSE = "Sparse"

TEXT_EMBEDDING_MODEL = "text-embedding-3-large"
JINAAI_EMBEDDING_MODEL = "jinaai/jina-embeddings-v2-small-en"
SPARSE_EMBEDDING_MODEL = "Qdrant/BM25"
